### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by metalefty**
ref. https://github.com/AlmaLinux/build-system/issues/58

Before update:
22 vulnerabilities (5 moderate, 13 high, 4 critical)

After update:
12 vulnerabilities (1 moderate, 7 high, 4 critical)

Further updates are currently difficult because some libraries stick to vulnerable version of other libraries.

I will perform tests to confirm this update break any workflow. Helps are welcome.

### CODE REVIEW

**Review by zklevsha — CHANGES_REQUESTED** [review]
Both Pretier and Tests are failed.

**Comment by metalefty** [comment]
Regarding prettier, this PR contains no code changes, so I believe prettier fail is not related to this change.

**Comment by metalefty** [comment]
Switched to Node 14 to run CI properly.

**Review by zklevsha — APPROVED** [review]
LGTM but we need someone to deploy and test it locally

**Review by maccelf — CHANGES_REQUESTED** [review]
Please update the version of Node js in the Dockerfile

**Comment by metalefty** [comment]
Updated to Node 16 both Dockerfile and GitHub workflow.

**Comment by maccelf** [comment]
Now I have this error in my container
 ```
App • Chaining "UI" Webpack config
frontend_1                   | ┌───────────────────────────────────────────────────┐
frontend_1                   | │          @quasar/cli update check failed          │
frontend_1                   | │        Try running with sudo or get access        │
frontend_1                   | │       to the local update config store via        │
frontend_1                   | │ sudo chown -R $USER:$(id -gn $USER) /root/.config │
frontend_1                   | └───────────────────────────────────────────────────┘
frontend_1                   | node:fs:590
frontend_1                   |   handleErrorFromBinding(ctx);
frontend_1                   |   ^
frontend_1                   | 
frontend_1                   | [  Error: permission denied, open '/code/.quasar/app.js'
frontend_1                   |   
frontend_1                   |   - node:fs:590 Object.openSync
frontend_1                   |     node:fs:590:3
frontend_1                   |   
frontend_1                   |   - node:fs:2202 Object.writeFileSync
frontend_1                   |     node:fs:2202:35
frontend_1                   |   
frontend_1                   |   - generator.js:68 
frontend_1                   |     [code]/[@quasar]/app/lib/generator.js:68:10
frontend_1                   |   
frontend_1                   |   - Array.forEach
frontend_1                   |   
frontend_1                   |   - generator.js:67 Generator.build
frontend_1                   |     [code]/[@quasar]/app/lib/generator.js:67:16
frontend_1                   |   
frontend_1                   |   - quasar-dev:284 runMain
frontend_1                   |     [code]/[@quasar]/app/bin/quasar-dev:284:17
frontend_1                   |   
frontend_1                   |   - task_queues:96 processTicksAndRejections
frontend_1                   |     node:internal/process/task_queues:96:5
frontend_1                   |   
frontend_1                   | ] {
frontend_1                   |   errno: -13,
frontend_1                   |   syscall: 'open',
frontend_1                   |   code: 'EACCES',
frontend_1                   |   path: '/code/.quasar/app.js'
frontend_1                   | }

```

**Comment by metalefty** [comment]
The updated Dockerfile worked for me.

```
$ docker build -t metalefty-albs-frontend:latest .
$ docker run --rm -it -v $(pwd):/code -p 8080:8080 metalefty-albs-frontend:latest
> albs-frontend@0.0.1 build
> quasar build


 Build mode........ spa
 Pkg quasar........ v2.12.3
 Pkg @quasar/app... v3.3.3
 Pkg webpack....... v5
 Debugging......... no
 Publishing........ no

 Configured browser support (>= 86.81% of global marketshare):
 · Chrome for Android >= 115
 · Firefox for Android >= 115
 · Android >= 115
 · Chrome >= 106
 · Edge >= 112
 · Firefox >= 106
 · iOS >= 15.2-15.3
 · Opera >= 96
 · Safari >= 15.6

 App • Chaining "UI" Webpack config
 App • Cleaned build artifact: "/code/dist/spa"
 App •  WAIT  • Compiling of "UI" in progress...
[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.

 App •  DONE  • "UI" compiled with success • 16849ms

 Summary for "UI" (only css/js/json)
 ╔══════════════════════════╤═══════════╤═══════════╗
 ║                    Asset │      Size │   Gzipped ║
 ╟──────────────────────────┼───────────┼───────────╢
 ║         122.4af73601.css │   1.10 KB │   0.55 KB ║
 ║         131.4d93f355.css │   0.40 KB │   0.26 KB ║
 ║         330.bd95b054.css │   0.17 KB │   0.13 KB ║
 ║         344.54b87ab6.css │   0.24 KB │   0.15 KB ║
 ║         524.3c7ff715.css │   0.04 KB │   0.06 KB ║
 ║         536.a7669346.css │   0.37 KB │   0.17 KB ║
 ║         547.50bbd69c.css │   0.67 KB │   0.32 KB ║
 ║         553.683b82a4.css │   0.12 KB │   0.12 KB ║
 ║          61.35f5235e.css │   0.09 KB │   0.08 KB ║
 ║         620.3a1b7376.css │   0.06 KB │   0.07 KB ║
 ║         652.2037abb7.css │   1.13 KB │   0.43 KB ║
 ║         705.5b672b83.css │   0.30 KB │   0.21 KB ║
 ║         765.12d74e36.css │   0.04 KB │   0.06 KB ║
 ║         821.5e16de27.css │   0.08 KB │   0.08 KB ║
 ║         850.fa0876a2.css │   0.58 KB │   0.26 KB ║
 ║          89.50bbd69c.css │   0.67 KB │   0.32 KB ║
 ║         app.31d6cfe0.css │   0.00 KB │   0.02 KB ║
 ║      vendor.1e3c02b2.css │ 194.67 KB │  34.44 KB ║
 ╟──────────────────────────┼───────────┼───────────╢
 ║          122.9f851866.js │  38.76 KB │   8.64 KB ║
 ║          131.51494391.js │   9.07 KB │   3.06 KB ║
 ║          330.c0a44dba.js │   9.68 KB │   2.97 KB ║
 ║          344.7c303472.js │  15.23 KB │   4.58 KB ║
 ║          481.04839a0a.js │   0.76 KB │   0.50 KB ║
 ║          524.d87740d3.js │   4.95 KB │   1.97 KB ║
 ║          536.c5b2868b.js │  16.09 KB │   4.56 KB ║
 ║          547.737ebe49.js │   7.99 KB │   2.58 KB ║
 ║          553.55654275.js │  13.21 KB │   3.87 KB ║
 ║           61.adf41648.js │   0.90 KB │   0.55 KB ║
 ║          620.af13de75.js │  13.64 KB │   3.76 KB ║
 ║          652.d8616fd9.js │   6.94 KB │   2.78 KB ║
 ║          659.9835e53f.js │   4.42 KB │   1.75 KB ║
 ║          705.af553cb5.js │  51.48 KB │  12.33 KB ║
 ║          765.66604db8.js │   7.76 KB │   2.53 KB ║
 ║          766.92881df1.js │   8.14 KB │   2.96 KB ║
 ║          821.3db236f1.js │   0.75 KB │   0.50 KB ║
 ║          846.358383f7.js │   0.80 KB │   0.54 KB ║
 ║          850.a24dbb94.js │  31.48 KB │   7.62 KB ║
 ║          app.2af67946.js │  19.58 KB │   6.90 KB ║
 ║ chunk-common.e9928ab1.js │  33.83 KB │   8.84 KB ║
 ║       vendor.04f6e15b.js │ 510.65 KB │ 168.35 KB ║
 ╚══════════════════════════╧═══════════╧═══════════╝

 Build succeeded

 Build mode........ spa
 Pkg quasar........ v2.12.3
 Pkg @quasar/app... v3.3.3
 Pkg webpack....... v5
 Debugging......... no
 Publishing........ no
 Transpiled JS..... yes (Babel)
 ==================
 Output folder..... /code/dist/spa

 Tip: Built files are meant to be served over an HTTP server
      Opening index.html over file:// won't work

 Tip: You can use "$ quasar serve" command to create a web server,
      both for testing or production. Type "$ quasar serve -h" for
      parameters. Also, an npm script (usually named "start") can
      be added for deployment environments.
      If you're using Vue Router "history" mode, don't forget to
      specify the "--history" parameter: "$ quasar serve --history"

```

**Review by maccelf — APPROVED** [review]

**Pull request merged**
